name: 发布到 npm
on:
  push:
    branches: '*'
    paths:
      - 'packages/core/**' # 主包
      - 'packages/dev-log/**' # 日志包
      - 'packages/check-version/**' # 版本检测包
      - 'package.json' # 全局的依赖信息

  workflow_dispatch: # 手动触发
    inputs:
      ref:
        description: '发布的分支（选填）'
        required: false
        default: ''
        type: string
      package:
        description: '要发布的包'
        required: true
        type: choice
        options:
          - all
          - core
          - dev-log
          - check-version
        default: 'all'

jobs:
  pub:
    # 在提交的代码包含 `version` 字样时才运行该动作
    # 或者手动触发
    name: |
      发布到 npm
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    # 复合条件判断（自动触发检查提交信息，手动触发直接放行）
    # startsWith(github.event.head_commit.message, 'version')
    # contains(github.event.inputs.version, '手动触发')
    # endsWith(github.event.head_commit.message, 'version')
    if: |
      (github.event_name == 'push' && startsWith(github.event.head_commit.message, 'version')) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: 代码检出
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}
          fetch-depth: 3

      - name: 初始化 Node 并设定 Node 版本
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: 安装 dependencies 依赖
        run: npm ci

      - name: 检测变更的包信息
        id: changed_packages
        run: |
          check_version() {
           local NAME=$1
           local ECHO_NAME="${1//-/_}" # 将 - 替换为 _
           local CHANGED=$(git diff --name-only HEAD^ HEAD | grep -q "^packages/${NAME}/" && npx @qqi/check-version name=$NAME  && echo 'true' || echo 'false' | tr -d '\n')
           if  [ "$CHANGED" != "false" ] && [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
             echo '手动触发判断'   
             if [ "${{ github.event.inputs.package }}" = "all" ] || [ "${{ github.event.inputs.package }}" = "${NAME}" ]; then
                echo "${ECHO_NAME}_changed=true" >> $GITHUB_OUTPUT
                return 0
              else
                echo "${ECHO_NAME}_changed=false" >> $GITHUB_OUTPUT
                return 0
             fi
           fi

           if [ "$CHANGED" != "false" ]; then
              echo "${ECHO_NAME}_changed=true" >> $GITHUB_OUTPUT
           else 
             echo "${ECHO_NAME}_changed=false" >> $GITHUB_OUTPUT
           fi
          }

          check_version core
          check_version dev-log
          check_version check-version

      - name: 检测设定的值
        run: |
          echo "${{ steps.changed_packages.outputs.core_changed }}"
          echo "${{ steps.changed_packages.outputs.dev_log_changed }}"
          echo "${{ steps.changed_packages.outputs.check_version_changed }}"
          chmod +x ./scripts/pub.sh

      - name: 构建  core code
        if: steps.changed_packages.outputs.core_changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          ./scripts/pub.sh core

      - name: 构建 dev log
        if: steps.changed_packages.outputs.dev-log_changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          ./scripts/pub.sh dev-log

      - name: 构建 check version
        if: steps.changed_packages.outputs.check_version_changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          ./scripts/pub.sh check-version
